version: '3.8'
services:
  django:
    image: tdhoan526/private:tot_nghiep_v1.1
    ports:
      - "80:80"
    #command: 
    environment:
      DATABASE_NAME: tot_nghiep
      DATABASE_USER: api_user
      DATABASE_PASSWORD: super_password
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      CPU_GRAPH: <iframe width="900" height="200" src="https://www.youtube.com/embed/RqfaTIWc3LQ?si=f6bjdWQdRktxFJl3" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
      MEMORY_GRAPH: <iframe width="900" height="200" src="https://www.youtube.com/embed/RqfaTIWc3LQ?si=f6bjdWQdRktxFJl3" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
      DISK_GRAPH: <iframe width="900" height="200" src="https://www.youtube.com/embed/RqfaTIWc3LQ?si=f6bjdWQdRktxFJl3" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
    command: bash -c python3 manage.py runserver 0.0.0.0:80
    depends_on:
      db:
        condition: service_healthy

    links:
      - db
      - grafana
      - prometheus
    networks:
      - network1
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: api_user
      MYSQL_PASSWORD: super_password
      MYSQL_DATABASE: tot_nghiep
    ports:
      - "3306:3306"
    healthcheck:
      test: "exit 0"
    volumes:
      #- /mnt/docker-compose/tot-nghiep/mysql/
      - ./mysql/:/var/lib/mysql
    networks:
      - network1

  prometheus:
    image: prom/prometheus:v2.36.2
    user: root
    volumes:
      - ./prometheus/config:/etc/prometheus/
      - ./prometheus/data:/prometheus
    deploy:
      resources:
          limits:
            memory: 1G
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
    - 9090:9090
    restart: always
    networks:
      - network1

  grafana:
    image: grafana/grafana
    user: root
    ports:
      - 3000:3000
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/config/grafana.ini:/etc/grafana/grafana.ini
    restart: always
    links:
      - db
      - prometheus
    networks:
      - network1

networks:
  network1: