# Generated by Django 5.0.2 on 2024-02-26 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='Services',
        ),
    ]
