# Generated by Django 5.0.2 on 2024-02-26 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servers',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cpu_model', models.CharField(default='0000000', max_length=50)),
                ('memory', models.CharField(default='0000000', max_length=50)),
                ('active_service', models.CharField(default='0000000', max_length=50)),
                ('disk', models.CharField(default='0000000', max_length=50)),
                ('status', models.CharField(default='0000000', max_length=50)),
                ('requested_user', models.CharField(default='0000000', max_length=50)),
            ],
            options={
                'db_table': 'servers',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('used_server', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=50)),
                ('service_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'services',
            },
        ),
    ]
