# Generated by Django 5.0.2 on 2024-02-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers_management', '0002_rename_service_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servers',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='services',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
