# Generated by Django 5.0.2 on 2024-02-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers_management', '0003_alter_servers_id_alter_services_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='servers',
            name='server_name',
            field=models.CharField(default='0000000', max_length=50),
        ),
    ]
