# Generated by Django 5.0.2 on 2024-03-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers_management', '0007_service_mapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servers',
            name='active_service',
            field=models.CharField(default='None', max_length=1000),
        ),
    ]
