# Generated by Django 5.0.2 on 2024-03-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers_management', '0008_alter_servers_active_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_mapping2',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('server_id', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'mapping_table2',
            },
        ),
        migrations.AlterField(
            model_name='servers',
            name='os',
            field=models.CharField(default='debian 12', max_length=50),
        ),
    ]
