# Generated by Django 5.0.2 on 2024-02-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servers',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('used_server', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=50)),
                ('service_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'server',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('used_server', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=50)),
                ('service_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'service',
            },
        ),
    ]
