# Generated by Django 5.0.2 on 2024-02-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servers',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='servers',
            name='service_name',
        ),
        migrations.RemoveField(
            model_name='servers',
            name='used_server',
        ),
        migrations.AddField(
            model_name='servers',
            name='active_service',
            field=models.CharField(default='0000000', max_length=50),
        ),
        migrations.AddField(
            model_name='servers',
            name='cpu_model',
            field=models.CharField(default='0000000', max_length=50),
        ),
        migrations.AddField(
            model_name='servers',
            name='disk',
            field=models.CharField(default='0000000', max_length=50),
        ),
        migrations.AddField(
            model_name='servers',
            name='memory',
            field=models.CharField(default='0000000', max_length=50),
        ),
        migrations.AddField(
            model_name='servers',
            name='requested_user',
            field=models.CharField(default='0000000', max_length=50),
        ),
        migrations.AddField(
            model_name='servers',
            name='status',
            field=models.CharField(default='0000000', max_length=50),
        ),
        migrations.AlterModelTable(
            name='servers',
            table='servers',
        ),
        migrations.AlterModelTable(
            name='service',
            table='services',
        ),
    ]
